lab1/Models/CalcModel.cs

namespace lab1.Data.Models
{
    public class CalcModel
    {
        public int a;
        public int b;
        public string sum;
        public string sub;
        public string mult;
        public string div;

        public CalcModel(int a, int b,string sum, string sub, string mult, string div)
        {
            this.a = a;
            this.b = b;
            this.sum = sum;
            this.sub = sub;
            this.mult = mult;
            this.div = div;
        }
    }
}

lab1/Controllers/CalculateController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using lab1.Data.Models;

namespace lab1.Data.Controllers
{
    public class CalculateController : Controller
    {
        private readonly Random random = new();
        private readonly int a;
        private readonly int b;
        private readonly string sum;
        private readonly string sub;
        private readonly string mult;
        private readonly string div;

        public CalculateController()
        {
            a = random.Next(0, 11);
            b = random.Next(0, 11);
            sum = $"{a} + {b} = {a + b}";
            sub = $"{a} - {b} = {a - b}";
            mult = $"{a} * {b} = {a * b}";
            div = b == 0 ? "Can't devide by 0" : $"{a} / {b} = {a / b}";
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult PassUsingModel()
        {
            var model = new CalcModel(a, b, sum, sub, mult, div);
            return View(model);
        }

        public ViewResult PassUsingViewData()
        {
            ViewData["a"] = a;
            ViewData["b"] = b;
            ViewData["sum"] = sum;
            ViewData["sub"] = sub;
            ViewData["mult"] = mult;
            ViewData["div"] = div;
            return View();
        }

        public ViewResult PassUsingViewBag()
        {
            ViewBag.a = a;
            ViewBag.b = b;
            ViewBag.sum = sum;
            ViewBag.sub = sub;
            ViewBag.mult = mult;
            ViewBag.div = div;
            return View();
        }

        public ViewResult AccessServiceDirectly()
        {            
            return View();
        }
    }
}

lab1/Views/Calculate/AccessServiceDirectly.cshtml
@inject lab1.Services.DirectAccess direct

@{
    ViewBag.Title = "AccessServiceDirectly - Backend1";
}
<h1>AccessServiceDirectly</h1>

<b>Rand value first:</b> @direct.a
<br />
<b>Rand value second:</b> @direct.b
<br />

<b>Add:</b>
<br />
@direct.sum
<br />

<b>Sub:</b>
<br />
@direct.sub
<br />

<b>Mult:</b>
<br />
@direct.mult
<br />

<b>Div:</b>
<br />
@direct.div
<br />

lab1/Views/Calculate/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Calc Service Demonstration</h1>
<ul>
    <li><a asp-controller="Calculate" asp-action="PassUsingModel">Using Model Calc</a></li>
    <li><a asp-controller="Calculate" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="Calculate" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="Calculate" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
</ul>

lab1/Views/Calculate/PassUsingModel.cshtml
@model lab1.Data.Models.CalcModel

@{
    ViewBag.Title = "PassUsingModel - Backend1";
}

<h1>PassUsingModel</h1>
<b>Rand value first:</b> @Model.a
<br />
<b>Rand value second:</b> @Model.b
<br />

<b>Add:</b>
<br />
@Model.sum
<br />

<b>Sub:</b>
<br />
@Model.sub
<br />

<b>Mult:</b>
<br />
@Model.mult
<br />

<b>Div:</b>
<br />
@Model.div
<br />

lab1/Views/Calculate/PassUsingViewBag.cshtml

@{
    ViewBag.Title = "PassUsingViewBag - Backend1";
}

<h1>PassUsingViewBag</h1>
<b>Rand value first:</b> @ViewBag.a
<br />
<b>Rand value second:</b> @ViewBag.b
<br />

<b>Add:</b>
<br />
@ViewBag.sum
<br />

<b>Sub:</b>
<br />
@ViewBag.sub
<br />

<b>Mult:</b>
<br />
@ViewBag.mult
<br />

<b>Div:</b>
<br />
@ViewBag.div
<br />

lab1/Views/Calculate/PassUsingViewData.cshtml
@model lab1.Data.Models.CalcModel

@{
    ViewBag.Title = "PassUsingViewData - Backend1";
}

<h1>PassUsingViewData</h1>
<b>Rand value first:</b> @ViewData["a"]
<br />
<b>Rand value second:</b> @ViewData["b"]
<br />

<b>Add:</b>
<br />
@ViewData["sum"]
<br />

<b>Sub:</b>
<br />
@ViewData["sub"]
<br />

<b>Mult:</b>
<br />
@ViewData["mult"]
<br />

<b>Div:</b>
<br />
@ViewData["div"]
<br />

lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <h2>Backend1</h2>
        <nav><a asp-controller="Calculate" asp-action="Index">Home</a></nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <hr />
        © 2021 - Backend1
    </footer>
</body>
</html>